[package]
authors = ["Jacob <jacob.lcs@qq.com>"]
edition = "2021"
name    = "svgo-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi        = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
quick-xml   = "0.37.2"
regex       = "1.11.1"
thiserror   = "2.0.11"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
