[package]
authors = ["Jacob <jacob.lcs@qq.com>"]
edition = "2021"
name    = "svgo-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi6 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
bumpalo     = { version = "3.17.0", features = ["collections"] }
napi        = { version = "2.16.17", features = ["napi6"] }
napi-derive = "2.16.13"
quick-xml   = "0.37.3"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
