/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RemoveDescOptions {
  /** Remove any `desc` elements, even if they have children. */
  removeAny: boolean
}
export interface PluginConfig {
  removeDesc: RemoveDescOptions
}
export interface OptimizeOptions {
  plugins: PluginConfig
}
export declare function optimize(inputXml: string, options: OptimizeOptions): string
