/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function optimize(inputXml: string): string

export declare function optimizeWithPlugins(inputXml: string, options: OptimizeWithPluginsOptions): string

export interface OptimizeWithPluginsOptions {
  /**
   * 要运行的插件列表（顺序生效），使用 svgo 的插件名：
   * removeDesc/removeDoctype/removeComments/removeXMLProcInst/removeMetadata/
   * moveElemsAttrsToGroup/removeEditorsNSData/removeTitle/addAttributesToSVGElement
   */
  plugins: Array<string>
  /** removeDesc: 对齐 svgo 的 removeAny */
  removeDescRemoveAny?: boolean
  /** removeComments: preservePatterns（每个字符串会作为正则表达式编译） */
  removeCommentsPreservePatterns?: Array<string>
  /** removeComments: preservePatterns = false */
  removeCommentsPreservePatternsDisabled?: boolean
  /** removeEditorsNSData: additionalNamespaces */
  removeEditorsNsDataAdditionalNamespaces?: Array<string>
  /**
   * addAttributesToSVGElement: attribute（字符串）
   * 支持两种格式：
   * 1) name            -> 输出为 name=""
   * 2) key=value       -> 输出为 key="value"
   */
  addAttributesToSvgElementAttribute?: string
  /**
   * addAttributesToSVGElement: attributes（字符串数组）
   * 每项支持格式：name 或 key=value
   */
  addAttributesToSvgElementAttributes?: Array<string>
  /** addClassesToSVGElement: className（字符串） */
  addClassesToSvgElementClassName?: string
  /** addClassesToSVGElement: classNames（字符串数组） */
  addClassesToSvgElementClassNames?: Array<string>
  /** cleanupAttrs */
  cleanupAttrsNewlines?: boolean
  cleanupAttrsTrim?: boolean
  cleanupAttrsSpaces?: boolean
  /** cleanupNumericValues */
  cleanupNumericValuesFloatPrecision?: number
  cleanupNumericValuesLeadingZero?: boolean
  cleanupNumericValuesDefaultPx?: boolean
  cleanupNumericValuesConvertToPx?: boolean
  /** cleanupListOfValues */
  cleanupListOfValuesFloatPrecision?: number
  cleanupListOfValuesLeadingZero?: boolean
  cleanupListOfValuesDefaultPx?: boolean
  cleanupListOfValuesConvertToPx?: boolean
  /** convertColors */
  convertColorsCurrentColor?: string
  convertColorsCurrentColorEnabled?: boolean
  convertColorsNames2Hex?: boolean
  convertColorsRgb2Hex?: boolean
  convertColorsConvertCase?: string
  convertColorsShorthex?: boolean
  convertColorsShortname?: boolean
  /** cleanupIds */
  cleanupIdsRemove?: boolean
  cleanupIdsMinify?: boolean
  cleanupIdsPreserve?: Array<string>
  cleanupIdsPreservePrefixes?: Array<string>
  cleanupIdsForce?: boolean
  /** convertShapeToPath */
  convertShapeToPathConvertArcs?: boolean
  /** convertStyleToAttrs */
  convertStyleToAttrsKeepImportant?: boolean
  /** mergePaths */
  mergePathsForce?: boolean
  /** prefixIds */
  prefixIdsPrefix?: string
  prefixIdsDelim?: string
  prefixIdsPrefixIds?: boolean
  prefixIdsPrefixClassNames?: boolean
  /** removeAttributesBySelector */
  removeAttributesBySelectorSelector?: string
  removeAttributesBySelectorAttributes?: Array<string>
  /** removeAttrs */
  removeAttrsAttrs?: Array<string>
  removeAttrsElemSeparator?: string
  removeAttrsPreserveCurrentColor?: boolean
  /** removeDeprecatedAttrs */
  removeDeprecatedAttrsRemoveUnsafe?: boolean
  /** removeElementsByAttr */
  removeElementsByAttrId?: Array<string>
  removeElementsByAttrClass?: Array<string>
  /** removeEmptyText */
  removeEmptyTextText?: boolean
  removeEmptyTextTspan?: boolean
  removeEmptyTextTref?: boolean
  /** removeHiddenElems */
  removeHiddenElemsIsHidden?: boolean
  removeHiddenElemsDisplayNone?: boolean
  removeHiddenElemsOpacity0?: boolean
  removeHiddenElemsCircleR0?: boolean
  removeHiddenElemsEllipseRx0?: boolean
  removeHiddenElemsEllipseRy0?: boolean
  removeHiddenElemsRectWidth0?: boolean
  removeHiddenElemsRectHeight0?: boolean
  removeHiddenElemsPatternWidth0?: boolean
  removeHiddenElemsPatternHeight0?: boolean
  removeHiddenElemsImageWidth0?: boolean
  removeHiddenElemsImageHeight0?: boolean
  removeHiddenElemsPathEmptyD?: boolean
  removeHiddenElemsPolylineEmptyPoints?: boolean
  removeHiddenElemsPolygonEmptyPoints?: boolean
  /** removeUnknownsAndDefaults */
  removeUnknownsAndDefaultsUnknownContent?: boolean
  removeUnknownsAndDefaultsUnknownAttrs?: boolean
  removeUnknownsAndDefaultsDefaultAttrs?: boolean
  removeUnknownsAndDefaultsDefaultMarkupDeclarations?: boolean
  removeUnknownsAndDefaultsUselessOverrides?: boolean
  removeUnknownsAndDefaultsKeepDataAttrs?: boolean
  removeUnknownsAndDefaultsKeepAriaAttrs?: boolean
  removeUnknownsAndDefaultsKeepRoleAttr?: boolean
  /** removeUselessStrokeAndFill */
  removeUselessStrokeAndFillStroke?: boolean
  removeUselessStrokeAndFillFill?: boolean
  removeUselessStrokeAndFillRemoveNone?: boolean
  /** removeXlink */
  removeXlinkIncludeLegacy?: boolean
  /** sortAttrs */
  sortAttrsOrder?: Array<string>
  sortAttrsXmlnsOrder?: string
}
